/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as EngagementRingsRouteImport } from './routes/engagement-rings'
import { Route as FineJewelryRouteImport } from './routes/fine-jewelry'
import { Route as MensRouteImport } from './routes/mens'
import { Route as RingBuilderRouteImport } from './routes/ring-builder'
import { Route as WeddingBandsRouteImport } from './routes/wedding-bands'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ApiConceptRenderRouteImport } from './routes/api/concept-render'
import { Route as ApiRingPreviewRouteImport } from './routes/api/ring-preview'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as RingBuilderIndexRouteImport } from './routes/ring-builder.index'
import { Route as RingBuilderShapeRouteImport } from './routes/ring-builder.shape'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRingsRoute = EngagementRingsRouteImport.update({
  id: '/engagement-rings',
  path: '/engagement-rings',
  getParentRoute: () => rootRouteImport,
} as any)
const FineJewelryRoute = FineJewelryRouteImport.update({
  id: '/fine-jewelry',
  path: '/fine-jewelry',
  getParentRoute: () => rootRouteImport,
} as any)
const MensRoute = MensRouteImport.update({
  id: '/mens',
  path: '/mens',
  getParentRoute: () => rootRouteImport,
} as any)
const RingBuilderRoute = RingBuilderRouteImport.update({
  id: '/ring-builder',
  path: '/ring-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingBandsRoute = WeddingBandsRouteImport.update({
  id: '/wedding-bands',
  path: '/wedding-bands',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConceptRenderRoute = ApiConceptRenderRouteImport.update({
  id: '/api/concept-render',
  path: '/api/concept-render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRingPreviewRoute = ApiRingPreviewRouteImport.update({
  id: '/api/ring-preview',
  path: '/api/ring-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RingBuilderIndexRoute = RingBuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RingBuilderRoute,
} as any)
const RingBuilderShapeRoute = RingBuilderShapeRouteImport.update({
  id: '/shape',
  path: '/shape',
  getParentRoute: () => RingBuilderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/engagement-rings': typeof EngagementRingsRoute
  '/fine-jewelry': typeof FineJewelryRoute
  '/mens': typeof MensRoute
  '/ring-builder': typeof RingBuilderRouteWithChildren
  '/wedding-bands': typeof WeddingBandsRoute
  '/wishlist': typeof WishlistRoute
  '/api/concept-render': typeof ApiConceptRenderRoute
  '/api/ring-preview': typeof ApiRingPreviewRoute
  '/product/$slug': typeof ProductSlugRoute
  '/ring-builder/shape': typeof RingBuilderShapeRoute
  '/ring-builder/': typeof RingBuilderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/engagement-rings': typeof EngagementRingsRoute
  '/fine-jewelry': typeof FineJewelryRoute
  '/mens': typeof MensRoute
  '/wedding-bands': typeof WeddingBandsRoute
  '/wishlist': typeof WishlistRoute
  '/api/concept-render': typeof ApiConceptRenderRoute
  '/api/ring-preview': typeof ApiRingPreviewRoute
  '/product/$slug': typeof ProductSlugRoute
  '/ring-builder/shape': typeof RingBuilderShapeRoute
  '/ring-builder': typeof RingBuilderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/engagement-rings': typeof EngagementRingsRoute
  '/fine-jewelry': typeof FineJewelryRoute
  '/mens': typeof MensRoute
  '/ring-builder': typeof RingBuilderRouteWithChildren
  '/wedding-bands': typeof WeddingBandsRoute
  '/wishlist': typeof WishlistRoute
  '/api/concept-render': typeof ApiConceptRenderRoute
  '/api/ring-preview': typeof ApiRingPreviewRoute
  '/product/$slug': typeof ProductSlugRoute
  '/ring-builder/shape': typeof RingBuilderShapeRoute
  '/ring-builder/': typeof RingBuilderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/engagement-rings'
    | '/fine-jewelry'
    | '/mens'
    | '/ring-builder'
    | '/wedding-bands'
    | '/wishlist'
    | '/api/concept-render'
    | '/api/ring-preview'
    | '/product/$slug'
    | '/ring-builder/shape'
    | '/ring-builder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/engagement-rings'
    | '/fine-jewelry'
    | '/mens'
    | '/wedding-bands'
    | '/wishlist'
    | '/api/concept-render'
    | '/api/ring-preview'
    | '/product/$slug'
    | '/ring-builder/shape'
    | '/ring-builder'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/engagement-rings'
    | '/fine-jewelry'
    | '/mens'
    | '/ring-builder'
    | '/wedding-bands'
    | '/wishlist'
    | '/api/concept-render'
    | '/api/ring-preview'
    | '/product/$slug'
    | '/ring-builder/shape'
    | '/ring-builder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  EngagementRingsRoute: typeof EngagementRingsRoute
  FineJewelryRoute: typeof FineJewelryRoute
  MensRoute: typeof MensRoute
  RingBuilderRoute: typeof RingBuilderRouteWithChildren
  WeddingBandsRoute: typeof WeddingBandsRoute
  WishlistRoute: typeof WishlistRoute
  ApiConceptRenderRoute: typeof ApiConceptRenderRoute
  ApiRingPreviewRoute: typeof ApiRingPreviewRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement-rings': {
      id: '/engagement-rings'
      path: '/engagement-rings'
      fullPath: '/engagement-rings'
      preLoaderRoute: typeof EngagementRingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fine-jewelry': {
      id: '/fine-jewelry'
      path: '/fine-jewelry'
      fullPath: '/fine-jewelry'
      preLoaderRoute: typeof FineJewelryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mens': {
      id: '/mens'
      path: '/mens'
      fullPath: '/mens'
      preLoaderRoute: typeof MensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ring-builder': {
      id: '/ring-builder'
      path: '/ring-builder'
      fullPath: '/ring-builder'
      preLoaderRoute: typeof RingBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-bands': {
      id: '/wedding-bands'
      path: '/wedding-bands'
      fullPath: '/wedding-bands'
      preLoaderRoute: typeof WeddingBandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/concept-render': {
      id: '/api/concept-render'
      path: '/api/concept-render'
      fullPath: '/api/concept-render'
      preLoaderRoute: typeof ApiConceptRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ring-preview': {
      id: '/api/ring-preview'
      path: '/api/ring-preview'
      fullPath: '/api/ring-preview'
      preLoaderRoute: typeof ApiRingPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ring-builder/': {
      id: '/ring-builder/'
      path: '/'
      fullPath: '/ring-builder/'
      preLoaderRoute: typeof RingBuilderIndexRouteImport
      parentRoute: typeof RingBuilderRoute
    }
    '/ring-builder/shape': {
      id: '/ring-builder/shape'
      path: '/shape'
      fullPath: '/ring-builder/shape'
      preLoaderRoute: typeof RingBuilderShapeRouteImport
      parentRoute: typeof RingBuilderRoute
    }
  }
}

interface RingBuilderRouteChildren {
  RingBuilderShapeRoute: typeof RingBuilderShapeRoute
  RingBuilderIndexRoute: typeof RingBuilderIndexRoute
}

const RingBuilderRouteChildren: RingBuilderRouteChildren = {
  RingBuilderShapeRoute: RingBuilderShapeRoute,
  RingBuilderIndexRoute: RingBuilderIndexRoute,
}

const RingBuilderRouteWithChildren = RingBuilderRoute._addFileChildren(
  RingBuilderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  EngagementRingsRoute: EngagementRingsRoute,
  FineJewelryRoute: FineJewelryRoute,
  MensRoute: MensRoute,
  RingBuilderRoute: RingBuilderRouteWithChildren,
  WeddingBandsRoute: WeddingBandsRoute,
  WishlistRoute: WishlistRoute,
  ApiConceptRenderRoute: ApiConceptRenderRoute,
  ApiRingPreviewRoute: ApiRingPreviewRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
