/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EngagementRingsRouteImport } from './routes/engagement-rings'
import { Route as FineJewelryRouteImport } from './routes/fine-jewelry'
import { Route as MensRouteImport } from './routes/mens'
import { Route as RingBuilderRouteImport } from './routes/ring-builder'
import { Route as WeddingBandsRouteImport } from './routes/wedding-bands'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRingsRoute = EngagementRingsRouteImport.update({
  id: '/engagement-rings',
  path: '/engagement-rings',
  getParentRoute: () => rootRouteImport,
} as any)
const FineJewelryRoute = FineJewelryRouteImport.update({
  id: '/fine-jewelry',
  path: '/fine-jewelry',
  getParentRoute: () => rootRouteImport,
} as any)
const MensRoute = MensRouteImport.update({
  id: '/mens',
  path: '/mens',
  getParentRoute: () => rootRouteImport,
} as any)
const RingBuilderRoute = RingBuilderRouteImport.update({
  id: '/ring-builder',
  path: '/ring-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingBandsRoute = WeddingBandsRouteImport.update({
  id: '/wedding-bands',
  path: '/wedding-bands',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engagement-rings': typeof EngagementRingsRoute
  '/fine-jewelry': typeof FineJewelryRoute
  '/mens': typeof MensRoute
  '/ring-builder': typeof RingBuilderRoute
  '/wedding-bands': typeof WeddingBandsRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/engagement-rings': typeof EngagementRingsRoute
  '/fine-jewelry': typeof FineJewelryRoute
  '/mens': typeof MensRoute
  '/ring-builder': typeof RingBuilderRoute
  '/wedding-bands': typeof WeddingBandsRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/engagement-rings': typeof EngagementRingsRoute
  '/fine-jewelry': typeof FineJewelryRoute
  '/mens': typeof MensRoute
  '/ring-builder': typeof RingBuilderRoute
  '/wedding-bands': typeof WeddingBandsRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/engagement-rings'
    | '/fine-jewelry'
    | '/mens'
    | '/ring-builder'
    | '/wedding-bands'
    | '/wishlist'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/engagement-rings'
    | '/fine-jewelry'
    | '/mens'
    | '/ring-builder'
    | '/wedding-bands'
    | '/wishlist'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/engagement-rings'
    | '/fine-jewelry'
    | '/mens'
    | '/ring-builder'
    | '/wedding-bands'
    | '/wishlist'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EngagementRingsRoute: typeof EngagementRingsRoute
  FineJewelryRoute: typeof FineJewelryRoute
  MensRoute: typeof MensRoute
  RingBuilderRoute: typeof RingBuilderRoute
  WeddingBandsRoute: typeof WeddingBandsRoute
  WishlistRoute: typeof WishlistRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement-rings': {
      id: '/engagement-rings'
      path: '/engagement-rings'
      fullPath: '/engagement-rings'
      preLoaderRoute: typeof EngagementRingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fine-jewelry': {
      id: '/fine-jewelry'
      path: '/fine-jewelry'
      fullPath: '/fine-jewelry'
      preLoaderRoute: typeof FineJewelryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mens': {
      id: '/mens'
      path: '/mens'
      fullPath: '/mens'
      preLoaderRoute: typeof MensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ring-builder': {
      id: '/ring-builder'
      path: '/ring-builder'
      fullPath: '/ring-builder'
      preLoaderRoute: typeof RingBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-bands': {
      id: '/wedding-bands'
      path: '/wedding-bands'
      fullPath: '/wedding-bands'
      preLoaderRoute: typeof WeddingBandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EngagementRingsRoute: EngagementRingsRoute,
  FineJewelryRoute: FineJewelryRoute,
  MensRoute: MensRoute,
  RingBuilderRoute: RingBuilderRoute,
  WeddingBandsRoute: WeddingBandsRoute,
  WishlistRoute: WishlistRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
